### ISSUE TITLE
ApplyPage breaks when you click exactly between two entries on an Autosuggest

### ISSUE THREAD

**Issue by subhankar-panda** [UCSDTESC/Check-in#73] opened 2018-08-23 16:53 UTC
When you click exactly between two universities on the university dropdown `react-autosuggest` errors out with this stack trace : 

![image](https://user-images.githubusercontent.com/23143381/44539933-05ee5700-a723-11e8-93e2-96382c957d94.png)

This is a library bug and we should probably just move over to [react-select](https://jedwatson.github.io/react-select/) or file a bug with `react-autosuggest`

**Comment by RedbackThomson** [comment] 2019-04-01 21:55
Seems like this may have been fixed in a new version of react-autosuggest. I cannot reproduce it.

**Closed** 2019-04-20 02:01 UTC
Labels: bug
